#!/bin/bash
echo THIS SCRIPT WAS CREATE BY ALEX
echo PLEASE ENTER COMMIT MESSAGE:
read user_comit_message
echo NOW ADDING ALL FILES
git add *
echo ====================
echo SUCCESSFULLY ADDED ALL FILES TO COMMIT
git status
git commit -m "$user_comit_message"
echo ====================
echo FILE SUCCESSFULLY ADDE
git push
echo ====================
echo PUSH SUCCESSFUL
