#!/usr/bin/env bash

# Find the PID and process name of processes containing the word "bash"
for pid in /proc/*/; do
    pid=${pid%/}
    pid=${pid##*/}
    if [[ -f /proc/"$pid"/comm ]]; then
        process_name=$(cat /proc/"$pid"/comm)
        if [[ "$process_name" == *bash* ]]; then
            echo "$pid $process_name"
        fi
    fi
done
