#!/usr/bin/env bash
#this a Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal

while 'true'; do
	echo "To infinityband beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
