#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:
#    displays 4 and then bad luck from China for the 4th loop iteration
#    displays 9 and then bad luck from Japan for the 9th loop iteration
#    displays 17 and then bad luck from Italy for the 17th loop iteration
Num=21
count=1
while [ $count -ne $Num ]
do
    case $count in
    5) echo "bad luck from China";;
    10) echo "bad luck from Japan";;
    18) echo "bad luck from Italy";;
    esac
    echo $count
    ((count++))
done
