#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
#   display hours from 0 to 12
#    display minutes from 1 to 59
count=13
Hour=0
while [ $count -ne $Hour ]
do
    echo "Hour: $Hour"
    for minute in {1..59}
    do
        echo "$minute"
    done
        ((Hour++))
done
